# Site settings
title: Andrew Sosa Guaita's Data Science Portfolio
description: A collection of personal projects
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://andrewsosag.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Sosa Guaita
user_description: I am currently pursuing a B.A. in Applied Mathematics at UC Berkeley, where I've developed a strong interest in applying data to solve real-world problems. I've led various data science projects, where I've turned complex datasets into practical solutions, and my internships at Driscoll's and Motorola Solutions have given me firsthand experience with handling data in a complex business environments. 
user_title: Student at UC Berkeley
email: andrew@sosacentral.com
twitter_username: lorem_ipsum
github_username:  andrewsosag
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
