cat > .github/workflows/deploy.yml << 'EOL'
name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
          
      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://andrewsosag:${GH_TOKEN}@github.com/andrewsosag/andrewsosag.github.io.git deploy
          rm -rf deploy/*
          cp -r out/* deploy/
          cd deploy
          touch .nojekyll
          git add .
          git commit -m "Deploy site"
          git push origin main
EOL